services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-damolak_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-damolak_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  redis:
    image: redis:8.4.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - appnet

  backend:
    build: ./backend
    image: temmytope/damolak-be:latest
    expose:
      - "8000"
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql+asyncpg://user:password@db:5432/damolak_db}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - appnet

  frontend:
    build: ./frontend
    image: temmytope/damolak-fe:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet: